main: aliuly\mtp\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD

name: MagicTelePortal
description: A simple portal plugin
version: 1.3.2-4
author: aliuly

commands:
  mtp:
    description: Create a portal
    usage: "/mtp [world|addr:port] [x y z]"
    permission: mtp.cmd.mtp

permissions:
  mtp.cmd.mtp:
    default: op
    description: "Allow to create portal"
  mtp.destroy:
    default: op
    description: Allow destruction of portals
